# Generated by Django 3.1.3 on 2021-01-20 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_todo_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
