# Generated by Django 3.1.3 on 2021-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=6)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
