# Generated by Django 3.1.3 on 2021-01-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210122_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
